import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full dark" style={{ colorScheme: "dark" }}>
      <body className={cn("flex flex-col min-h-screen", font.className)}>
        <Navbar />
        <main className="flex-grow flex justify-center">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
